name: "DevSecOps Pipeline (SCA, SAST, DAST)"

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Pozwala uruchomić proces ręcznie

jobs:
  # 1. SCA - Skanowanie bibliotek (Software Composition Analysis)
  dependency-check:
    name: SCA (Snyk)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # KROK 1: Instalacja środowiska Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Juice Shop wymaga nowszej wersji Node.js

      # KROK 2: Instalacja bibliotek (to stworzy node_modules)
      - name: Install dependencies
        run: npm install --package-lock-only # Szybsza wersja, która generuje drzewo zależności

      # KROK 3: Teraz Snyk zadziała
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  # 2. SAST - Statyczna analiza kodu źródłowego
  static-analysis:
    name: SAST (Semgrep)
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep scan --config auto --error # --error sprawia, że błędy blokują pipeline
